### ISSUE TITLE
How to reverse proxy nomad and consul UI

### ISSUE THREAD

**Issue by blmhemu** [sofixa/nomad-examples#1]
Hello ! I have read the excellent guide on https://atodorov.me/2021/03/27/using-traefik-on-nomad/
I would like to access my nomad and consul UIs (localhost:4646 and localhost:8500) behind the traefik reverse proxy like (nomad.example.com and consul.example.com)

Is there a way to accomplish the above ?

I was about to email you but found this repo just in time.

**Comment by sofixa** [comment]
@blmhemu yep, they're regular Consul services so all you need to do is add a specific router for them. Did you get it to work? If not, i can whip up an example.

**Comment by blmhemu** [comment]
Hey ! Thanks for the response. Yes, I used the consul's DNS to achieve this.
